---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vlrrywof/repositories/mercadolibre/
    - /bin/cp -R * $DEPLOYPATH
    - cp .htaccess $DEPLOYPATH
    # - cp .env $DEPLOYPATH
    - cp .styleci.yml $DEPLOYPATH
