<?php

return [

    'PUBLIC_ID' => env('WOMPI_SANDBOX_PUBLIC_ID'),
    'PRIVATE_ID' => env('WOMPI_SANDBOX_PRIVATE_ID'),
    'MERCHANTS' => env('WOMPI_SANDBOX_MERCHANTS'),
    'TOKEN_CART' => env('WOMPI_SANDBOX_TOKEN_CARD'),
    'TRANSITION' => env('WOMPI_SANDBOX_TRANSITION'),
    'TRANSITION_SEARCH' => env('WOMPI_SANDBOX_TRANSITION_SEARCH')



];
